Added guide for setting up a volume
shadeform/docs pull request #7
Opened 2024-12-17 23:43 UTC by Elden123

…r /volumes/types

2024-12-17 23:44 UTC, Elden123 commented on openapi.yaml
> +      type: array
I noticed that we had this set up to show it returned a single item, it actually returns an array though.

2024-12-19 05:21 UTC, cholical requested changes

2024-12-19 05:21 UTC, cholical commented on guides/attachvolume.mdx
> +
Can we add a line here that says "Currently, volumes can only be attached to instances in the same cloud provider and region. Multi-cloud volumes are an upcoming feature."

2024-12-19 05:21 UTC, cholical commented on guides/attachvolume.mdx
> +<Note> "volume_ids" must be an array of size one. This is because we only allow attaching one volume to one instance right now. Attaching multiple volumes to a single instance is a feature we may add
Can we change from "we may add" to "we will add"

2024-12-19 05:21 UTC, cholical commented on guides/attachvolume.mdx
> +
Can we add a new step here that is "Step 5: Mount the volume to a file system" and then show the commands:

sudo mkdir /dev/sdb
sudo mkfs.ext4 /dev/sdb
sudo mount -t ext4 /dev/sdb /mnt/sdb/
sudo chown -R shadeform:shadeform /mnt/sdb/

2024-12-19 05:21 UTC, cholical commented on guides/attachvolume.mdx
> +lsblk
Let's also add the example output of lsblk

2024-12-19 20:38 UTC, cholical approved these changes

2024-12-19 20:38 UTC, cholical commented on guides/attachvolume.mdx
> +sudo mkdir /dev/vdb
We don't actually create /dev/vdb. It's not a real folder but a file system representation of a device. This is something that linux does for devices.

2024-12-19 20:38 UTC, merged